name: DevelopBranchAutoRelease

on:
  push:
    branches: [ develop ]

jobs:
  canaryRelease:
    runs-on: ubuntu-latest
    env:
      Build: non
      NewTagName: non
    steps:
      - name: チェックアウト
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: リリース用のタグを削除と作成
        run: |
            LatestTagName=$(git describe --tags $(git rev-list --tags --max-count=1))
            git tag -d ${url} $LatestTagName

            Build=$(git rev-list --count HEAD)
            NewTagName=Canary_$Build
            echo "NewTagName=${NewTagName}" >> $GITHUB_ENV
            echo "Build=${Build}" >> $GITHUB_ENV

            git tag $NewTagName

            url="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}"
            git push ${url} :$LatestTagName
            git push ${url} $NewTagName

      - name: 不要なファイルの削除
        run: |
          rm -r .github 
          rm -r .git 
          rm .gitignore README.md icons/originalIcon.png

      - name: バージョンをコミット番号に変更
        run: |
          Build=${{ env.Build }}
          sed -i -e 's/chrome.runtime.getManifest().version.split(".")/'${Build}'/' toolbarPopup/popup.js
          sed -i -e 's/chrome.runtime.getManifest().version/"Canary Build '${Build}'"/' toolbarPopup/popup.js
      
      - name: zip作成
        run: |
          zip -r Ny0bi_Tool_${{ github.sha }}.zip .
      
      - name: リリース
        uses: softprops/action-gh-release@v1
        with:
          files: Ny0bi_Tool_${{ github.sha }}.zip
          prerelease: true
          body: |
            # Canary版は、開発ブランチで変更がプッシュされるごとに自動で作成されるバージョンです。
            
            **簡単に言うと、Canary版は開発途中のバージョンなので、常用には適していません。 自己責任で利用してください。**

            詳しくは、[Ny0bi Tool WiKiのページをご覧ください。](https://github.com/CoreNion/Ny0bi_Tool/wiki/Ny0bi-Tool%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%83%BB%E3%82%A2%E3%83%83%E3%83%97%E3%83%87%E3%83%BC%E3%83%88%E6%96%B9%E6%B3%95(%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E6%96%B9%E5%BC%8F)#canary%E7%89%88)

            **[現在開発中の機能](https://github.com/CoreNion/Ny0bi_Tool/tree/develop#%E7%8F%BE%E5%9C%A8%E9%96%8B%E7%99%BA%E4%B8%AD%E3%81%AE%E6%A9%9F%E8%83%BD)**
            
            変更履歴は[コミット一覧](https://github.com/CoreNion/Ny0bi_Tool/commits/develop)を閲覧してください。
          name: Canary Build ${{ env.Build }}
          tag_name: ${{ env.NewTagName }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: タグが消えたことによりできたdraftを削除 
        uses: hugo19941994/delete-draft-releases@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
